### ISSUE TITLE
WaitForNextTickAsync doesn't seem to return during graceful shutdown

### ISSUE THREAD

**Issue by goenning** [sgbj/crontimer#4]
I have a cronjob that looks like the following.

When I shutdown the app using Ctrl+C on my laptop, the service does not print the `DoSomethingCronJob stopped`, it seems like it's still stuck in the loop waiting for the next tick.

I'd expect the loop to break and allow me to perform whatever I need for a safe shutdown

```csharp
public class DoSomethingCronJob : BackgroundService
{
    private readonly ILogger _logger;

    public DoSomethingCronJob(ILogger<DoSomethingCronJob> logger)
    {
        _logger = logger ?? throw new ArgumentNullException(nameof(logger));
    }

    protected override async Task ExecuteAsync(CancellationToken cancellationToken)
    {
        _logger.LogInformation("DoSomethingCronJob is starting.");

        using var timer = new CronTimer("0 0 * * *", TimeZoneInfo.Utc);

        while (await timer.WaitForNextTickAsync(cancellationToken))
        {
            _logger.LogInformation("doing something");
        }

        _logger.LogInformation("DoSomethingCronJob stopped.");
    }
}
```

**Comment by sgbj** [comment]
Hi goenning, sorry for the late response.

Is your application hanging at shutdown, or is it shutting down immediately without printing `DoSomethingCronJob stopped`? Pressing Ctrl+C should cause WaitForNextTickAsync to throw an OperationCanceledException, which is what I observed when running your example code locally.

If you'd like to perform some cleanup, I recommend adding a try catch like in [this example](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/host/hosted-services#asynchronous-timed-background-task).

**Comment by goenning** [comment]
hey @sgbj you're right, if I try/catch it works. Thanks
